id: 0f133a08d3874c7888aa25be5b4ba8e2
initial_creation_type: ocr
source_metadata:
  volumes:
    e133901e433e43eeb09b782a1950deae:
      base_file: v096.txt
      image_group_id: I1PD95942
      title: ཚད་མ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1198
      volume_number: 97
